

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
      - source: mdm-rules
        target: /app/config/mdm-rules.json
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hapi"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

configs:
  hapi:
     file: ./hapi.application.yaml
  mdm-rules:
     file: mdm-rules.json
