spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
hapi:
  fhir:
    fhir_version: R4
    mdm_enabled: true
    mdm_rules_enabled: true
    implementationguides:
      ph_core:
        name: fhir.ph.core
        version: 0.2.0
        packageUrl: https://build.fhir.org/ig/UP-Manila-SILab/ph-core/package.tgz
        reloadExisting: false
        installMode: STORE_AND_INSTALL
        fetchDependencies: true
      ph_erefferal:
        name: fhir.ph.ereferral
        version: 0.1.0
        packageUrl: file:///app/config/pheref-patched.tgz
        reloadExisting: true
        installMode: STORE_AND_INSTALL
        fetchDependencies: true
